### ISSUE TITLE
defaultValue doesn't get set in the dialog

### ISSUE THREAD

**Issue by jonnitto** [Flowpack/Flowpack.NodeTemplates#18]
If a property has a `defaultValue` set, this value doesn't get set in the creation dialog

**Comment by dimaip** [comment]
It is a missing feature, it was never supported there, but makes a lot of sense.
PRs are welcome!

**Comment by jonnitto** [comment]
Is this more a thing in the Neos.UI?

**Comment by dimaip** [comment]
Yes, naturally. I think I replied from the phone and didn't look at the repo :)
Could you open an issues there?

**Comment by jonnitto** [comment]
Of course. I definitely have to dive into the UI, so I can contribute to it. 👍

**Comment by jonnitto** [comment]
https://github.com/neos/neos-ui/issues/2129
