### ISSUE TITLE
how to add childNodes to NodeType of type ContentCollection

### ISSUE THREAD

**Issue by Lemmork** [Flowpack/Flowpack.NodeTemplates#19]
Hi, I have a content element which supertypes Neos.Neos:ContentCollection.
Therefore I don't have a named childNode of type ContentCollection.
I tried something like this, to add childNodes directly to my node, but it did not work.

```
'Vendor.XYGrid:Row':
  superTypes:
    'Neos.Neos:Content': true
    'Neos.Neos:ContentCollection': true
  ui:
   ...
    options:
      template:
         childNodes:
              column1:
                type: 'Vendor.XYGrid:Column'
              column2:
                type: 'Vendor.XYGrid:Column'
```

**Comment by dimaip** [comment]
Hi! Could the problem be caused by wrong indentation?

Also perhaps this link would be interesting to you: https://github.com/psmb/Sfi.Grid/blob/master/Configuration/NodeTypes.yaml#L17

**Comment by Lemmork** [comment]
Hi @dimaip ,

thanks for the example. Now it works for me. Probably it was an indention problem.
