### ISSUE TITLE
Integrate the rest of the editors

### ISSUE THREAD

**Issue by jonnitto** [Flowpack/Flowpack.NodeTemplates#2]
At the moment, not all editors are available in the creation dialog.

**Comment by dimaip** [comment]
Hey, this issue is related to the new UI itself, this package has nothing to do with it. Can you please re-open it there? https://github.com/neos/neos-ui/issues/

**Comment by jonnitto** [comment]
Not exactly. For example, the datetime editor is available in the new UI, but not in the creating dialog. The same with the image editor…

**Comment by jonnitto** [comment]
https://github.com/neos/neos-ui/issues/1034
