### ISSUE TITLE
Feature Request: Generate configuration from existing node

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/Flowpack.NodeTemplates#24]
While I think that NodeTemplates is a great package, I find the according templates a little cumbersome to configure due to the fact that there can be deep nesting.

I think it would be a good idea to create a setting "development mode" for the package and then add an additional inspector tab to Document nodes, displaying the node structure in the way that you could copy it to the Node Type definition.

This way, you could create a node that suits your needs, copy the definition and adjust (e.g. pre-defined property values).

What do you think? We might be willing to (help) funding this, so an estimate would be great.

**Comment by dimaip** [comment]
Hey! So basically you want to be able to take existing document/content nodes structure and use it as template?

**Comment by lorenzulrich** [comment]
Yes, indeed. In a way, I would like to have the structure tree (but including properties) of a document node exported in the format NodeTemplates can use it.

**Comment by daniellienert** [comment]
Sounds interesting. But I would not put it in an inspector tab, as this is nothing an editor could use. I would rather add a command controller action to export the tree beneath a given node.

**Comment by lorenzulrich** [comment]
This is also a possibility. As I initially stated, my suggestion was adding a configuration (similar to the `Neos.Ui` package that has a frontend development mode) that enables this inspector tab. So during integration you can easily use this (without copying node identifiers to the CLI and so on) and afterwards you disable it.

**Comment by lorenzulrich** [comment]
@Sebobo Yes, this is exactly what I need, and having it as CLI command is a good solution. I will comment over there.
