### ISSUE TITLE
uriPathSegment cannot be set via template

### ISSUE THREAD

**Issue by theilm** [Flowpack/Flowpack.NodeTemplates#25]
At the moment, the uriPathSegment property of a document is always generated by the TemplatingDocumentTitleNodeCreationHandler; thus, it's not possible to set it via a NodeTemplate. We should only generate it, if it is not set by the NodeTemplate.

**Comment by jonnitto** [comment]
I think this issue can be closed. WDYT, @daniellienert?

**Comment by daniellienert** [comment]
I guess so

**Comment by jonnitto** [comment]
@daniellienert So do it ;-) I've no rights to do that
