### ISSUE TITLE
Childnodes max deep

### ISSUE THREAD

**Issue by Azilla030** [Flowpack/Flowpack.NodeTemplates#32]
Hi, I miss the feature where you can adjust the maximum child nodes that could appear.

**Comment by theilm** [comment]
Hi @Azilla030, 
does this help you?
https://github.com/Flowpack/Flowpack.NodeTemplates/blob/master/Configuration/Settings.yaml#L15

**Comment by Azilla030** [comment]
But this is an general setting for every child nodes can I give this just one node type?

**Comment by theilm** [comment]
Sorry, missed your follow up question. It is a general setting.
