### ISSUE TITLE
BUG: In case of an Exception dont create any nodes

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/Flowpack.NodeTemplates#35]
If the template is malformed, all created nodes should be deleted, or better: A template should be first evaluated and expanded to a big array and then only rendered into the node tree not in the same run.

Separating the processes would make the code also easier testable, and the template less coupled the the old content repository implementation.

**Comment by theilm** [comment]
Thanks for the bug report.
Concerning separation of the processes: That's probably needed for the ESCR anyway; but it would be breaking, I guess. Right now, you have access to the current node and the parent node in the EEL context. If the template is evaluated and expanded to a array first, the nodes are not available yet and thus not accessible in the EEL context: https://github.com/Flowpack/Flowpack.NodeTemplates#eel-context-variables
What do you think?

**Comment by mhsdesign** [comment]
Hmm indeed too bad. But i must say in my current rather complex usecase i have found no real use for `parentNode` and the `currentNode` (the triggeringNode is enough for me ....)

Can you think of a real usecase?
