### ISSUE TITLE
Discussion: Future of extensibility in light of Neos 9.0. Drop the signal?

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/Flowpack.NodeTemplates#50]
@theilm you introduced a concept for extension with this pr:
https://github.com/Flowpack/Flowpack.NodeTemplates/pull/15

since we need to refactor a lot for 9.0 i want to make sure we dont need to go to extra lengths to keep supporting a feature if is not really needed.

What are your opinions. Did you ever use the extensibility and for which usecase?

**Comment by theilm** [comment]
Hi @mhsdesign, I never used this extensibility point in a production project. The use case I had in mind was something like editorial templates like showcased here:
https://github.com/mindscreen/neos-nodetemplates-demo/blob/master/Configuration/NodeTypes.EditorialTemplate.yaml
https://github.com/mindscreen/neos-nodetemplates-demo/blob/master/Classes/Service/ChildNodeCopyService.php

I think it will make easier to drop the extension point - and I am fine with it.

**Comment by mhsdesign** [comment]
Supi ;) 

Also i think any legit new functionality can be merged directly into the core ;)
