### ISSUE TITLE
Adjust conditions to Fusion - "if" instead of "when"

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.NodeTemplates#8]
The property of conditions is currently named "when" which is a bit confusing as there was no "when" before in Neos. Is there reason for that?

@theilm: What do you think about renaming it to "if" which would be consistent with the naming in fusion. 
Or even to "@if" to denote - like in Fusion - that this is a meta property.
An then - maybe adopt the complete fusion notation and allow multiple if statements with `@if.<identifier>: <condition>`

**Comment by theilm** [comment]
Hi @daniellienert, we wanted the naming to be as declarative as possible. See https://discuss.neos.io/t/rfc-node-templates/715
I understand your point and it's always good to reduce confusion. We should discuss it the declarative mood is worth the possible confusion. On the other hand: This is not Fusion, it is a configuration file. I do not think we should rebuild Fusion in YAML.
The ampersand is not used in configuration so far as far as I remember? I do not think that it is necessary as all properties are configuration keys (type, withItems, ...).
@dimaip Could you join the discussion as the Ansible-inspired syntax was your idea?

**Comment by dimaip** [comment]
Yes, as Thomas said, it was a conscious decision to use declarative syntax (if -> when, forEach -> withItems). We are describing the desired shape of nodes, not the imperative steps needed to get there.
If most of you don't find this idea really fitting, we could add aliases to support both namings, but I would prefer to just leave it as is if possible.

**Comment by daniellienert** [comment]
Thanks guys, just wanted to know where the vocabulary is coming from.
